### ISSUE TITLE
[clive] should it stay or should it go?

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#11]
clive is the software that we're using to validate pyvideo data json files. I figured I'd throw it in the same repository for now since the two will grow at the same time and it's a lot less work if they're in the same repo.

At some point p, it'll probably be better if they were in separate repositories.

This issue covers figuring out how to figure out whether we're at that point p and then figure out what to do.

**Comment by willkg** [comment]
It should go, but after we've got schemas and things a bit more stable and we're not making sweeping changes still. At that point, clive development should slow down.

**Comment by logston** [comment]
@willkg & @codersquid Can you chime in on this https://github.com/pytube/pyvideo-data/pull/8 ?

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
