### ISSUE TITLE
recover related_urls data

### ISSUE THREAD

**Issue by codersquid** [pyvideo/pyvideo-data#111]
In pyvideo.org we have related_urls in the video scheme, but not in the data here. related_urls were added manually, by me, and there aren't that many of them. Typically I'd add a link to slides, ipython notebooks, repos. I don't know the utility of that field, so maybe we can drop it? Close this issue if that's the disposition.

If it is not, someone could write a script based on existing scripts that goes through and extracts the related_urls from the existing pyvideo.org site to make a PR. If this is done, I'd like someone to do a trial run, then have a review of the script. And then, we can decide whether it makes sense to have a big PR and merge everything all at once, or whether it is better to do some PRs with manual oversite.

**Comment by willkg** [comment]
One issue is that there's no place in the schema for this data, so we need to add it.

Should we name the field "related_urls"? How about "resources"? Or "references"? Or something else? What's closer to the kind of data we're putting in there?

**Comment by willkg** [comment]
Once we figure out what to name the field, I'll fix clive to support the schema change and then getting help adding related urls from pyvideo would be super.

**Comment by codersquid** [comment]
I think "resources", as a list of dictionaries containing "url" and "description" is good enough for now and possibly for a long time.

I usually link things like
- repository related to the talk
- talk slides
- jupyter (nee ipython) notebook for the talk

In the past I may have linked an author's account somewhere such as github, twitter, etc but I have decided that is too generic and shouldn't go with a specific talk.

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
