### ISSUE TITLE
pycon-apac-2015 has no videos

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#112]
There are no videos in the pycon-apac-2015 directory. I'm not sure why offhand.

This issue covers getting the video data for that conference.

**Comment by codersquid** [comment]
I think I created the category and was waiting for the conference to post the videos. I got over excited because of reading someone's report about the conference, iirc.

**Comment by piotrbulinski** [comment]
I've added missing video data. Please let me know if the format is OK. If not, let's figure out how it can be improved (and then add this info to the `CONTRIBUTING.rst`).
