### ISSUE TITLE
document how to make a reference to this data

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#114]
If this data is ever used in a research project, I think the researcher needs a way to refer to a specific version of this data.

This issue covers talking to someone who does that work and establish whether there are conventions for this sort of thing already and/or what we need to facilitate proper references.

**Comment by codersquid** [comment]
We can look at best practices provided by groups like https://www.datacite.org/ and we can get DOIs for our releases by using github's zenodo integration https://guides.github.com/activities/citable-code/

**Comment by codersquid** [comment]
- https://www.force11.org/group/joint-declaration-data-citation-principles-final for some general principles to follow
- http://schema.datacite.org/meta/kernel-3/index.html I don't want to use xml, but would read their schema for suggestions of the information we could provide in a CITATION file perhaps.

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
