### ISSUE TITLE
[djangocon-2015] Extract speakers from title

### ISSUE THREAD

**Issue by redapple** [pyvideo/pyvideo-data#115]
See https://github.com/pyvideo/pyvideo-data/pull/47/commits/40d9896d2f097397e4e34543f22bb8ffd6e8e785 for motivation

**Comment by pfrcks** [comment]
@redapple Looks interesting. Will like to work on it.

**Comment by redapple** [comment]
@pfrcks , actually I forgot to update this issue. It was fixed in https://github.com/pyvideo/pyvideo-data/pull/120

**Comment by redapple** [comment]
@pfrcks , thanks for the interest in fixing the data!
There are other similar issues you could pick up instead.

**Comment by pfrcks** [comment]
@redapple What methodology did you utilize to do this? Was it done manually, by separating the speakers from the data?
And sure, I will start taking a look into other issues :)

**Comment by redapple** [comment]
@pfrcks , I used a simple script with a regular expression,
something like

```
import re
from clive import lib

data = lib.load_json_data('data/djangocon-2015/videos')
for path, info in data:
    m = re.search('^(?P<title>.+)\s+by\s+(?P<speakers>.+)$',
                  info.get('title', ''))
    if m:
        info['title'] = m.group("title").strip()
        info['speakers'] = [s.strip() for s in m.group("speakers").strip().split(',')]

lib.save_json_data(data)
```
