### ISSUE TITLE
fix honza's name

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#123]
Honza Král's name is spelled in two ways across our data:
1. The correct way.
2. The all-ascii way: Honza Kral.

We should fix his name in the places it's wrong.

**Comment by redapple** [comment]
@willkg ,
I only found 2 places where his name was not "Honza Král"

There's also `data/djangocon-eu-2010` where he spoke (cf. `data/djangocon-eu-2010/videos/djangoconeu-honzakrl224flv.json`), but that conference's data needs much more work (https://github.com/pyvideo/pyvideo-data/issues/125)

**Comment by willkg** [comment]
I think you're right.

There's a lot of conferences where we had crap data and/or didn't take the time to really normalize the data across the fields we had.

At some future point, I want to start writing up reports of the data quality. Where data quality is things like:
1. do all videos have at least one speaker?
2. do all videos have at least a summary?
3. do any urls in a video kick up an HTTP 404?
4. ...

I've been focusing on other things as we bootstrap this project, so I haven't spent time on that.

I'll write up an issue for it now. Even if I don't have time to think about it, other people might.
