### ISSUE TITLE
DjangoCon EU 2010: fix titles, summaries, descriptions and speakers

### ISSUE THREAD

**Issue by redapple** [pyvideo/pyvideo-data#125]
Data in `data/djangocon-eu-2010/videos/` is virtually empty, with only video links, and title being the video files names.

Talks information for the conference can be found:
- http://djangode.pbworks.com/w/page/25534898/Presentations (dug it out from https://web.archive.org/web/20110531051833/http://2010.djangocon.eu/blog/rss/) 
- http://lanyrd.com/2010/djangocon-eu/schedule/

**Comment by codersquid** [comment]
I think this is one of the events we rescued from blip.tv and the data from those events is going to be like this. I would like help with all of them, if possible. Getting the files from our rackspace cdn to archive.org would also be nice.

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
