### ISSUE TITLE
close down pyvideo/pyvideo-data

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#139]
The https://github.com/pytube/pyvideo-data fork is becoming the official fork and we're passing everything off to @logston.

This issue covers all the things we need to do to transition properly.

(Copying the todo items here.)
- [x] clear the PR queue (@willkg)
- [x] deprecate this repository
- [x] figure out how to reparent pytube/data repo in github so that pull requests to the repo there don't automatically get made to here. It's a github thing that will confuse people. (@logston)
- [ ] write a blog post and link it on pyvideo.org (needs discussion) (@willkg)
- [x] in progress: transition the pyvideo.org domain to @logston or the PSF (@willkg, @codersquid)
- [ ] figure out what to do with clive and any other bits that I half-did (needs a list of bits and discussion about what to do about them)
- [x] figure out what to do with the pyvideo donated rackspace account
- [ ] in progress: move videos from rackspace CDN to archive.org (@logston)
- [ ] announce the end of pyvideoorg twitter account (@willkg)

**Comment by willkg** [comment]
Bah--spelled @logston wrong in the description. Doing this comment so Paul gets a github ping.

**Comment by willkg** [comment]
Off the top of my head, I think we need to do the following:
1. [ ] deprecate this repository
2. [ ] write a blog post and link it on pyvideo.org (needs discussion)
3. [ ] transition the pyvideo.org domain to @logston or the PSF (needs discussion)
4. [ ] figure out what to do with clive and any other bits that I half-did (needs a list of bits and discussion about what to do about them)
5. [ ] transition pyvideoorg twitter account

Does that list seem right? What's missing?

**Comment by codersquid** [comment]
- [ ] figure out what to do with the pyvideo donated rackspace account (needs discussion)

**Comment by codersquid** [comment]
Re pyvideo.org domain transferral. I emailed some board members about it. The PSF board is meeting in two weeks, and we can send a request to the board list asking for them to take ownership.

I propose that we send them a request:
- PSF to take over pyvideo.org
- PSF to agree that pyvideo.org follows community guidelines (make a readme or something in pyvideo repo)
- PSF to give @logston 's gandi account technical ownership.

**Comment by codersquid** [comment]
- [ ] figure out how to reparent pytube/data repo in github so that pull requests to the repo there don't automatically get made to here. It's a github thing that will confuse people.

@logston heads up, this is something that we might need to ask github for, unless they have made it easier to do these days.

**Comment by logston** [comment]
@willkg @codersquid  Great. That seems about right. I've responded to @codersquid's email regarding some of this stuff. The few points that I have input on are:
- transition pyvideoorg twitter account
- pyvideo donated rackspace account
- reparent pytube/data

I'm not sure we'll have a pytube twitter account. For ease of transition, I think we should probably close the pyvideo twitter account. 

As for the rackspace account, our main concern is getting the videos off of that account (that are served from rackspace) and onto archive.org.

As for reparenting, yes; that'd be great. I'm wondering how to do that as I ran into the issue myself. I can reach out to github and I'll report back here.

**Comment by logston** [comment]
Sent an email to github regarding reparenting just now.

**Comment by logston** [comment]
@codersquid @willkg Before you close down this repo, can you pull in the data related PRs? I'd hate to loose that work.

**Comment by willkg** [comment]
@logston When you say "pull in the data related PRs", what do you mean by that?

**Comment by logston** [comment]
Yeah, there are 4 open PRs that touch data (rather than code). Could those be merged?

**Comment by willkg** [comment]
Ahh... ok. I was telling them to redo the PRs in your fork.

**Comment by willkg** [comment]
Ok. I went through the pytube/pyvideo-data commits to make sure none of these were merged there already, then skimmed the changes and landed all the PRs.

**Comment by willkg** [comment]
I updated the issue description with a rollup of all the todo items, current status and who's responsible for those items. Kick me if that doesn't look right.

**Comment by logston** [comment]
Looks good. Thanks.

**Comment by codersquid** [comment]
@willkg I'd rather leave the twitter account for archival purposes. If we remove it all the posts will be lost.

**Comment by codersquid** [comment]
@logston about the videos archived on rackspace, are any of your crew working on that? (I had the impression yes, but want to check)

**Comment by codersquid** [comment]
Also, I'll keep the rackspace account. A while back I checked with the rackspace team that it is okay to use the account for open source/community video activities in general and Carl sometimes uses it to help debconf or other conferences.

**Comment by logston** [comment]
@codersquid Just created an issue to move data: https://github.com/pytube/data/issues/23

**Comment by zerok** [comment]
Hi :)

I was just about to write a mail to the list regarding what should be the canonical repository from now on. I guess that's decided now ;)

 What would be the advantage of removing the Twitter account? IMHO keeping it around would (as @codersquid already mentioned) serve an archive'ish (not English, I know ;) ) purpose but even more we could prevent others hijacking it which would allow us to move back to the pyvideo naming if perhaps desirable within the future :)

**Comment by codersquid** [comment]
Re pyvideo.org domain. The PSF board has replied. They'll take over the registration and @logston will be added to the registrar account so that he can manage dns records and such. I'll check that off.

**Comment by logston** [comment]
@codersquid Great. Thanks!

**Comment by willkg** [comment]
We successfully transferred everything and pyvideo lives on!
