### ISSUE TITLE
figure out language values

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#18]
We're currently doing the language name in English as the value for the language field. That's not great. We should probably switch to a better standard. Maybe iso-639-1?

**Comment by khorn** [comment]
The only other option besides using one of the ISO-639 variants would be IETF language tags (https://en.wikipedia.org/wiki/IETF_language_tag), but I don't see much benefit to the added complexity.

Probably starting with ISO-639-1 is the way to go.  It seems like it would be less disruptive to add things to the language field than to subtract from it later.  So best to start with the simplest thing.

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
