### ISSUE TITLE
markdown or reST

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#22]
Currently summary and description data is formatted with "markdown". We're using very basic elements that should work across the various markdown flavors, but it's probably the case that we'll hit one that's icky at some point.

When we converted from HTML to markdown in pyvideo a few years ago, we did so because more people were familiar and enthusiastic about editing in markdown than in reST. We've been using markdown ever since.

This issue covers figuring out whether to switch to reST for summaries and descriptions.

If we decide to switch, we should create two new issues: one to enhance the validator to validate reST in summary and description and one to convert from markdown to reST.

If we decide not to switch, we should figure out how to validate markdown in summary and description.

Current summary (March 21st, 2016):

**markdown**

pros:
- easy to use for our use case (lists, headers and occasionally links)
- generally people are familiar with markdown or at least are less fearful of markdown given its ubiquity
- we're using it now and have been for some time and haven't had any issues

cons:
- there are multiple markdown flavors, though I'm not sure this is an issue for our data set since we're primarily using lists, headers and occasionally links
- poorer tooling because of multiple markdown flavors?

**restructured text**

pros:
- easy to use for our use case (lists, headers and occasionally links)
- the tools are great and we can output to multiple formats (we've never had a need for this so far)
- better integration with the kinds of static site generators that might be used for the next pyvideo.org?
- very extensible (we've never needed to extend the markup)
- everyone who's commented in the markdown vs. reST issue is pro-reST

cons:
- seems like there's more fear about restructured text vs. markdown which might lead to fewer people helping (I think this would be hard to measure and I'm not sure we'd notice if we're affected by it)

**Comment by khorn** [comment]
The following is purely opinion:

In general, I prefer reST over markdown, primarily because:
- reST is more extensible
- reST handles generating output other than HTML much better

OTOH, markdown is really nice if all you want to do is generate snippets of HTML.  So for me the question is, will this data be used purely for HTML, or will it ever be used to generate anything else?

If markdown is selected, then there shouuld definitely be a decision made as to _which_ flavor of markdown is officially supported (w.r.t. the validator).

If reST is selected, I can totally help out with converting things.  I have some experience with mass conversion of stuff to reST.  The hard part IMO would actually be getting a parse tree out of the python markdown module (I'm assuming that's what would be used to parse the markdown).

**Comment by logston** [comment]
I have the same opinions about reST as @khorn does above;
- reST is more extensible
- reST handles generating output other than HTML much better

Plus, I feel like you can represent more complex documents (even when rendered to HTML) in reST.

The following is fact but I'm not sure how much weight it should actually hold in this discussion:
- reST is the markup used for Python

> The markup used for the Python documentation is reStructuredText,
> (https://docs.python.org/devguide/documenting.html)

Personally, I want to restrict the markup format to reST but my gut says that would cut down on PRs contributing new data. For example, I could easily see someone reading the docs, seeing that reST must be used when contributing data, and saying "whelp, this PR ain't happening"; myself would be included in that group of people a few years ago. And I want the barrier to entry for contributing data to be as low as possible. 

So, I'd like to make a suggestion: content types. You can contribute data in reST, markdown, plaintext, etc. but you have to specify a content type in the JSON object. If you don't, maybe reST could be assumed and validators would default to that markup? And a restriction could be that all content for a given video (description, title, summary, etc.) have to be parseable by the validator specified (or defaulted to) by the content type. Thoughts?

**Comment by willkg** [comment]
The actual conversion itself should be pretty straight-forward, so I don't think we need to factor that into which format we decide on. We used pandoc when we converted from HTML to markdown and that worked fine. We could do the same here.

I don't think there's a compelling reason to support multiple markups. I'd want to wait for evidence of this actually happening with pyvideo-data before we think about what to do about it. We're only using a markup for summaries and descriptions. Generally, the markup is limited to involves lists, headers and--very occasionally--links. It's pretty minor.

I think the point about reST being good at outputting to other formats is interesting. I haven't encountered use cases for this so far. Maybe someone's writing a book? Maybe a PDF version of a static site much like ReadTheDocs has PDF versions of documentation? It's interesting.

I'm going to send a link to this issue to the mailing list in case there are other people with helpful perspectives that aren't watching the issue.

**Comment by willkg** [comment]
I added a summary of where I think we're at to the description.

@logston, @khorn: Does that summary look fair? Is it missing anything?

**Comment by logston** [comment]
@willkg looks good :+1:

**Comment by codersquid** [comment]
Depending on what we scrape we don't get any kind of markup. In practice, I'd scrape a conference site (or use their api if available) and scrape something like youtube.

I don't want to force rST. I think it will reduce contributions. I would rather allow people to make PRs that are sloppy (but pass minimal validation) and those can be refined by follow-up PRs. We'll get data a lot faster that way.

(what the heck, I'm not getting notification emails)

**Comment by willkg** [comment]
This discussion seems pretty done. I think we should:
1. switch everything from Markdown to reST
2. when we document the schema state that the summary and description fields are in reST, but if it doesn't parse, then to treat it as an unformatted text blob
3. when we add validation for reST, we should make it a warning and not an error for Travis--i.e. no PR should fail to validate because of reST issues

I think that keeps a good balance of making it easy for people to add data and expectations for the shape of the data we have.

Does that sound ok? If so, I'll write up the new issues and close this out.

**Comment by codersquid** [comment]
Okay with me.

**Comment by logston** [comment]
Sounds good to me too.

**Comment by willkg** [comment]
Issue #27 covers converting existing video data.

The other two we can do when we get there. Closing this out. Thank you!

**Comment by willkg** [comment]
Issue #28 covers validating reST in summary and description.
