### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by willkg** [pyvideo/pyvideo-data#9]
We need documentation on the following things:
1. what is pyvideo-data?
2. what infrastructure exists and how does it work?
3. where does this community hang out?
4. how does someone assemble data for a conference? tips, tricks, tools, ...

**Comment by khorn** [comment]
What form do you envision this taking? A Sphinx project? A bunch of text files?

This is something I can maybe help out with.

**Comment by khorn** [comment]
Ah, reading #10 I'm going to assume this means a Sphinx proj.

**Comment by willkg** [comment]
There's a `docs/` directory which has the beginnings of the docs. It's a Sphinx project.

I think going with that seems like a good idea for now. If we end up with needs that don't work, we can always change it.

I suspect the first 3 items are documentable now. Item 4 might not be because it's still in flux.

**Comment by khorn** [comment]
I'm not seeing the `/docs` directory.  Are you sure it's been pushed to github?

**Comment by willkg** [comment]
@khorn Bah. You're right--it's just in my local repository. I'll push what I have with some fixes to make it easier to work on this bug. Sorry about that!

**Comment by willkg** [comment]
@khorn I threw everything I have so far in PR #25. Want to do a quick review of that? Then we can land it and you can base your changes on it.

As a side note, I'm not convinced the things I thought we should document in the issue description are the right things. I threw together that list off the top of my head. If you want to change things around, that's cool.

**Comment by khorn** [comment]
:+1: Looks like a good place to start from.

**Comment by willkg** [comment]
Awesome--thank you!

**Comment by willkg** [comment]
Closing this out since this repository is no longer active.
